### ISSUE TITLE
Settings doesnt scrolls

### ISSUE THREAD

**Issue by robertoprubio** [you-apps/RecordYou#191] opened 2023-08-24 10:18 UTC
### Steps to reproduce

1. Enter app settings
2. Scroll down with the finger
3. The settings doesnt scrolls in portrait and also in landscape 

### Expected behavior

App settings scrolls

### Actual behavior

Settings doesnt sca

### Record You version

7.0 (15)

### Android version

13

### Other details

OnePlus 8 pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment] 2023-08-24 10:29
Duplicate of #182

**Closed by Bnyro** 2023-08-24 10:29 UTC
Labels: bug
